apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petstore-allan
  description: The petstore API allan
  tags:
    - store
    - rest
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
    - url: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml
      title: API Spec
      icon: code
spec:
  type: api
  lifecycle: experimental
  owner: team-c
  definition: |
    openapi: 3.0.1
    info:
      title: OpenAPI not found
      version: 1.0.0
    paths:
      /oas-not-found:
        put:
          requestBody:
            content:
              application/json:
                schema: {}
            required: true
          responses:
            default:
              description: Ihu
              content: {}
